let a=20;
let b=50;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log("addition result is:",a+b);
console.log("subtraction result is:",a-b);
console.log("Multiplication result is:",a*b);
console.log("Division result is:",a/b);
console.log("Remainder result is:",a%b);
const c=15;
const d=25;
console.log(c>d);
console.log(c<d);
console.log(c==d);
console.log(c!=d);
console.log(a&&b);
console.log(a||b);
